version: "2"

services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      - CLIENT_SERVER=localhost
      - CLIENT_PORT=3000
  client:
    build: ./client
    ports:
      - "3030:3000"
    depends_on:
      - server
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=8080
